<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="F_HasContext" Id="0f378c4d-9ea6-4349-a6f6-3a335eee26ce" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_HasContext : BOOL
VAR_INPUT
	nContext: DWORD;
	nSearchContext: DWORD;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_HasContext:= (nContext > 0) AND (((nContext AND nSearchContext) > 0) OR (nSearchContext = E_DataSourceContext.eContext_Unknown));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>