<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="FB_TcMessageSuccess" Id="bd97662d-c5fa-4826-bd68-8c39c619dd3d" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TcMessageSuccess EXTENDS FB_TcMessage
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="f1e04add-15ea-4350-bb10-d6f3c3c04512">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode: BOOL; // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF NOT bInCopyCode THEN
	SUPER^.CreateEx(Tc3_EventLogger.SUCCESS_EVENT, 0);
END_IF]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>