<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="FB_TcMessageSuccess" Id="702e8019-ea2d-47c2-b31e-2f80950fc831" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TcMessageSuccess EXTENDS FB_TcMessage
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="883517f1-544f-4d0c-a89e-96f1a2eba83b">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode: BOOL; // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF NOT bInCopyCode THEN
	SUPER^.CreateEx(Tc3_EventLogger.SUCCESS_EVENT, 0);
END_IF]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>