<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="F_AlyTimestampToLocalTime" Id="d4cb0e88-f526-4c27-b4db-a7cd1d65fed1" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_AlyTimestampToLocalTime : ULINT
VAR_INPUT
	tTimestamp: ULINT;
END_VAR
VAR
	tFileTime: T_FILETIME;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[tFileTime:= DCTIME64_TO_Filetime(tTimestamp);
F_AlyTimestampToLocalTime:= ULARGE_TO_ULINT(ULARGE_INTEGER(tFileTime.dwHighDateTime, tFileTime.dwLowDateTime));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>