<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="F_DCTimestructToFileTime" Id="c367ff7a-5078-4a1d-9fb1-d2125281bc55" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DCTimestructToFileTime : ULINT
VAR_INPUT
	dtTimestamp: DCTIMESTRUCT;
END_VAR
VAR
	dcTime: T_DCTIME64;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[dcTime:= DCTIMESTRUCT_TO_DCTIME64(dtTimestamp);
F_DCTimestructToFileTime:= F_AlyTimestampToFileTime(dcTime);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>