<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="F_DCTimestructToFileTime" Id="6467ce87-136b-4b44-8c29-f9d612764d9c" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DCTimestructToFileTime : ULINT
VAR_INPUT
	dtTimestamp: DCTIMESTRUCT;
END_VAR
VAR
	dcTime: T_DCTIME64;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[dcTime:= DCTIMESTRUCT_TO_DCTIME64(dtTimestamp);
F_DCTimestructToFileTime:= F_AlyTimestampToFileTime(dcTime);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>