<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="F_DCTimestructToFileTime" Id="781619b6-f88f-406c-aa85-d030aa8dbc6e" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DCTimestructToFileTime : ULINT
VAR_INPUT
	dtTimestamp: DCTIMESTRUCT;
END_VAR
VAR
	dcTime: T_DCTIME64;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[dcTime:= DCTIMESTRUCT_TO_DCTIME64(dtTimestamp);
F_DCTimestructToFileTime:= F_AlyTimestampToFileTime(dcTime);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>